### ISSUE TITLE
Wont let me use any commands

### ISSUE THREAD

**Issue by MagmaJoxe** [austinpilz/FridayThe13th#11]
hi, ive downloaded the plugin and put it in my plugins folder, reloaded and when i do /f13 nothing happens. Im pretty new to plugins and i dont know what the hells going on aha, appreciate it if you could give me some help

**Comment by austinpilz** [comment]
You probably don't have any of the required dependencies installed. Please look at the setup guide on the wiki and make sure you have all of the required dependcies plugins installed.

**Comment by MagmaJoxe** [comment]
Thanks!
