### ISSUE TITLE
Weird rendering

### ISSUE THREAD

**Issue by MagmaJoxe** [austinpilz/FridayThe13th#12]
Whenever we spawn into a match we have to break blocks to load chunks, got any solutions? thanks

**Comment by MagmaJoxe** [comment]
Also when we die we get sent to the void and we are stuck until someone leaves the match.

**Comment by austinpilz** [comment]
The world rending is an issue on the part of your server, so I would check it's configuration as well as that of Multiverse. F13 doesn't do anything but teleport you around, it doesn't have any say in how worlds are loaded. 

Did you set the return point correctly? When you die and there are other players still playing, you're teleported to a random spawn point you defined as a spectator.

**Comment by MagmaJoxe** [comment]
Ok, And yes, everything is set up correctly

**Comment by MagmaJoxe** [comment]
Everything seems fine in the config :/ weird. I've found nothing about this on the internet either :/

**Comment by austinpilz** [comment]
Hm I'm not sure what to tell you then, nobody else has experienced that issue. You're running 1.12? Are there any console errors when it teleports you?

Do you have some sort of anti cheat plugin?

**Comment by MagmaJoxe** [comment]
I have no anti cheat plugin, and I am running 1.12. I didn't check console, ill try and get someone on to test it with me

**Comment by MagmaJoxe** [comment]
![2017-08-03_15 05 27](https://user-images.githubusercontent.com/30659470/28925684-78ff972c-785d-11e7-9be0-8683fbe6b49e.png) i've just tried with my friend, now we can't even play :I

**Comment by austinpilz** [comment]
That is really odd! Sadly, that's completely outside of my control as Spigot handles the teleportation and world rendering

**Comment by austinpilz** [comment]
You're welcome to give it a try on f13mc.com and see how it works on there

**Comment by MagmaJoxe** [comment]
![2017-08-03_15 18 10](https://user-images.githubusercontent.com/30659470/28926210-00c8b926-785f-11e7-8418-c197f515a2e2.png)

**Comment by MagmaJoxe** [comment]
Ok, what i just posted there is the glitchy rendering i originally encountered

**Comment by MagmaJoxe** [comment]
I've had a play around on that server ip you sent me and i find it amazing. I really wish i could set one of these up for people to play on :( oh well, ill direct my f13 and minecraft fans to that server 👍

**Comment by austinpilz** [comment]
Glad to hear you enjoyed it! Such a bummer to hear it has an issue on your server. I'm looking to push and update tomorrow or Saturday, so give that a shot
