### ISSUE TITLE
No map load

### ISSUE THREAD

**Issue by VelaGamesGR** [austinpilz/FridayThe13th#16]
Hello,i love this F13 plugin but we have an issue to our server. When the game starts all the players cant move we are on the sky and nobody can move. We see no map only the sky. Spawn points are inside the boundary. If they weren't inside the boundaries the plugin wouldnt let us place spawn points. 
We removed every possible plugin that could block the f13 tp but still nothing we are not able to play, 
![2017-09-05_01 19 53](https://user-images.githubusercontent.com/31635193/30039346-2dca1536-91d8-11e7-8c51-912c37fb04cf.png)
![2017-09-05_01 20 13](https://user-images.githubusercontent.com/31635193/30039347-2dcdbbdc-91d8-11e7-80fe-3740b426070e.png)

it spawns us on sky. I will report every plugin we currently have.
1)ActionBarAPI
2)Arconix 
3)Better Combat
4)ChairsStairs
5)Citizens
6) clearlag 
7)Colored signs
8)Coreprotect
9)corpseReborn 
10)custom sound manager
11)essentialsX chat 
12) essentialsX group manager 
13) F13
14)holographic displays 
15)kitadder
16)login security 
17)ProtocolLib
18)SideBar API
19)Vault

**Comment by austinpilz** [comment]
- Are you on 1.12.1?
- Is the spawn points in the same world as the waiting room?
- Does it complain when it teleports you into the waiting room?
- Are there any console errors when it teleports you to begin the game?

**Comment by VelaGamesGR** [comment]
1) im on 12 version not 1.12.1
2) yeah they are on the same world
3) no
4) no

**Comment by VelaGamesGR** [comment]
Ok so the problem was that the waiting room and the arena were in the same world. Plugin now works good. Thanks for your time

**Comment by VelaGamesGR** [comment]
Hello again. We tried to play the plugin with some friends and they weren't able to spawn it was always putting them on the sky. Me and my friend spawned normally so we set the plugin again and now it spawns everyone well but counselors don't have permission to open chests and use the phone and Jason spawns without the weapons. Do you have any idea with this is happening? We need this plugin fixed because it's the main server mini game and we promised to our fans that we will add it (we have YouTube channels). We could even pay you if you could join our server and set it up well. This plugin is really important for us because everyone is waiting for it

**Comment by austinpilz** [comment]
I totally understand.

Please update to Spigot 1.12.1 before hand, then test and let me know. If you're still having issues, message me on Discord austinpilz#4989 - I can come on and help you out.

**Comment by VelaGamesGR** [comment]
We are on 1.12.1 version since 1.12 didn't worked so I don't know what is going on. I'm definitely gonna add you. I'm really happy that you are willing to help. Thanks a lot I will add you on discord
