### ISSUE TITLE
Game time config option broken

### ISSUE THREAD

**Issue by cfr** [austinpilz/FridayThe13th#18]
`config.yml/GameTimeInSeconds` does not work, round is four minutes regardless actual setting.

**Comment by cfr** [comment]
As I see it is calculated now... [GameManager.java#L417](https://github.com/austinpilz/FridayThe13th/blob/d0070871bb524fc24fadde708cc4b2396b67becd/src/main/java/com/AustinPilz/FridayThe13th/Manager/Game/GameManager.java#L417)

Maybe add option to set minimum time limit?

**Comment by austinpilz** [comment]
Correct - the game time is calculated based on the MPC (minutes per counselor) which is defined per arena. Total Time = Num Counselors * Arena MPC. 

I'll add minimum time limit to the next update!
