### ISSUE TITLE
Strengths and weaknesses

### ISSUE THREAD

**Issue by pantera09cat** [austinpilz/FridayThe13th#19]
Hi, I always play at your server and I like to say some strenghs and weakness (in my opinion)

**Strenghs:**
- A lot of maps
- No lag
- A lot of skins
- A lot of habilities
- Beatiful lobby
- Music

Weakness:
- Some bugs (Jason can't break some doors)
- Can't scape by police
- Can't scape by car
- Some maps doesn't have Tommy's call
- How can I throw axes? (with the hability)

I love your server, don't stop working!!

pantera09cat

**Comment by austinpilz** [comment]
Hey! Thanks for playing, I'm glad you're enjoying it.

- I am working on the issue where Jason can't break some doors. I'm sorry about that one!
- Escape points are in the works and coming soon!
- All maps have Tommy Call points. At the beginning of every game, a random phone is selected. You might have to look around the map to find the right phone.
- The throw perk throws the axe on the last hit that kills your victim. It'll actually toss the item and it'll spin through the air.

**Comment by pantera09cat** [comment]
All right, thanks for your answer! :D
I can't wait for more updates. I did videos to promote your server (pantera09cat in Youtube).

Good job! :D
