### ISSUE TITLE
Door Breaking

### ISSUE THREAD

**Issue by austinpilz** [austinpilz/FridayThe13th#22]
Issue where sometimes Jason cannot break specific doors. 

User reports indicate that reloading will solve the issues.

**Comment by pantera09cat** [comment]
I hope it gets fixed soon. People take advantage of that. Also, sometimes when you jump out a window you bug with a bed or with an object and go below the map with the redstone circuit.
Can't wait for updates, well done Austin!

**Comment by austinpilz** [comment]
Issue fixed, come on f13mc.com and check it out :)
