### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by pantera09cat** [austinpilz/FridayThe13th#23]
Hi Austin!

These days I was playing at your server (as usual xD) and it has been very funny.
But again I have some bugs to repair and improvements to tell you. I hope it is not annoying.

**Bugs:**
- Sometimes, when you across a window and there is and object behind, you stay suffocated in the wall. Then you die or stay trapped under the map.
- When you start as Jason in Crystal Lake, you get bugged a little on the lake.
- In Crystal Lake I never have seen Tommy's Jarvis call.

**Improvements**
- Police's call could be interesting and easy to update.
- Your own skin is never changed. Only the others are changed.

Thanks for your attention. I'm very happy with your work, so see you on server!
I wait your answer :D

**Comment by austinpilz** [comment]
Hi! Thank you so much for the bug reports and suggestions, I always really appreciate them as they help make the game even better!

I am aware of the window jump issue and would expect a fix for that in the next update. 

Crystal lake absolutely has the phones, there’s a lot that it randomly picks from - but I’ll follow up to verify. The glitching on the lake is new, I’ll have to look at that. 

The skin updates cannot update for you to see, only other players. It’s just with how the Minecraft client works. Other players can see your skin, but you won’t ever be able to see your own. 

Police and escape points are coming in the next update!

**Comment by pantera09cat** [comment]
Okey  Austin!

Thanks for your opinion. As you see I'm like a helper hahaha
Can't wait for your updates, great work!!! :D
