### ISSUE TITLE
Tommy's call in Crystal Lake

### ISSUE THREAD

**Issue by pantera09cat** [austinpilz/FridayThe13th#24]
Austin,

I know that you are working the last things I told you. But I would like to tell you that I NEVER have seen Tomm's call in Crystal Lake, only in the other maps. I play a lot on your server and I am convinced. My friends told me the same and it will be funnier if we fix this.

Thank you very much for always answer me and for working on this original server. See you! :D

**Comment by austinpilz** [comment]
Hi! 

I will head on right now and verify there are phones, and re-add them to the arena if not. Sorry about that, thanks for letting me know :)
