### ISSUE TITLE
Invisible glitch

### ISSUE THREAD

**Issue by pantera09cat** [austinpilz/FridayThe13th#26]
Hi Austin!

I don't know why and how but sometimes I get invisible at spawn. Then, when I start a party I continue invisible so people can't see me. I send you an image with that. 

See you and Merry Christmas!!
![eje](https://user-images.githubusercontent.com/32229868/34339254-f9a7fb6e-e971-11e7-94cd-f365f1160180.png)

**Comment by pantera09cat** [comment]
Also, in a party, we can't see the right box (time, who's jason, etc)

**Comment by austinpilz** [comment]
Hey! I've noticed this issue - I'm working on it now. Thank you for letting me know

**Comment by pantera09cat** [comment]
You are welcome. I'm not the only one with this probleme (invisibility at spawn and in game).
Also, the games end when Jason kills everybody because there isn't time :(

**Comment by austinpilz** [comment]
If you had on now, I fixed the invisibility issue. I may need to come on and "/heal" you, but it won't turn you invisible anymore. 

What arena are you referencing? If there are fewer players the overall game time is shorter. Is this what you mean?

**Comment by austinpilz** [comment]
@pantera09cat fixed this :) If you go on now, nobody becomes invisible anymore. Thanks so much for letting me know!

**Comment by pantera09cat** [comment]
No Austin, there isn't right box so there's no time. It means infinite games.
Sorry for not answer, I'm out home. See you!

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________
