### ISSUE TITLE
XP glitch

### ISSUE THREAD

**Issue by pantera09cat** [austinpilz/FridayThe13th#27]
Hi Austin!

Today I left a party being Jason and my XP were glitched, you can see it in my photo. Can you fix it? I want Jason Retro and with this XP it's imposible haha xD (I'm only Jason V)

Another thing, when I used the boat in Crystal Lake it has suffocated in the wall. In my next video you will see it. Is it a glitch? Or just bad luck? 

Thanks for your attention, great updates!!
![eje](https://user-images.githubusercontent.com/32229868/35356491-e2aa9e02-0150-11e8-8cef-276c20ee61dc.png)

**Comment by austinpilz** [comment]
Can you send me your UUID so I can fix that for you? So sorry about that

**Comment by pantera09cat** [comment]
What is UUID?

Obtener Outlook para Android<https://aka.ms/ghei36>



De: Austin Pilz
Enviado: jueves, 25 de enero 0:54
Asunto: Re: [austinpilz/FridayThe13th] XP glitch (#27)
Para: austinpilz/FridayThe13th
Cc: pantera09cat, Author


Can you send me your UUID so I can fix that for you? So sorry about that

**Comment by austinpilz** [comment]
Your UUID is a unique identifier that follows you. Since you can change your username, your uuid is permanent. 

https://mcuuid.net

Enter your username on that site and send me the uuid with the dashes in it please. That’s how your info is stored in the F13 database

**Comment by pantera09cat** [comment]
Okey, here is it:

- Full UUID: 90d77aaa-91f8-4e52-83c1-377ecdefa51c
- Trimmed UUID: 90d77aaa91f84e5283c1377ecdefa51c
- Name History: pantera09cat (changed as of: 3rd Jun, 2017)
                          jandro09cat

I was road to level 10.

Another thing, I lost the video where the boat was glitched on the lake. I remember that I put the gasoline and the propellant from the water, it could be the problem? You would do us a help if you revise it.

Thanks Austin!!

**Comment by austinpilz** [comment]
You should be all good :)
