### ISSUE TITLE
Boat's glitch

### ISSUE THREAD

**Issue by pantera09cat** [austinpilz/FridayThe13th#28]
Hi Austin!

When you fix the boat, it always spawns under the water, so it is usless! You can see this in my photo.
Can you fix it? Thanks!!

pantera09cat
![eje](https://user-images.githubusercontent.com/32229868/35880674-db559e26-0b7e-11e8-856f-96aed6c6e524.png)

**Comment by austinpilz** [comment]
Taking a look at this now, sorry about that

**Comment by austinpilz** [comment]
Fixed this :)
