### ISSUE TITLE
Help me with a plugin please

### ISSUE THREAD

**Issue by Raikiry** [austinpilz/FridayThe13th#31]
I have problem with a plugin , when game starts i can t do nothing as jason any abilities and scoreboard is stuck , i Have installed all dependencies .... Sometimes it kick me from the server when game starts , and when i m write /f13 leave it isn´t teleport me to lobby
![image](https://user-images.githubusercontent.com/36795003/36641762-9d7f2f3e-1a35-11e8-840b-c33092a38471.png)

**Comment by austinpilz** [comment]
Please provide server information, Spigot version, plugin list, and RAM. Also, please include console output when the game begins

**Comment by Raikiry** [comment]
I have Spigot 1.12 my RAM is 3560 MB , Plugins : Premium BedWars , Essentials , Fast Login , Mbedwars , authme , hide and seek , Kit Battle , ItemJoin , DeluxeMenus , Murder Mystery , BuildBattlePro , WorldEdit , Action Bar API , Holographic Displays , Scoreboard API , ProtocolLib , Corpses Reborn , CustomSoundManagerAPI , Interactables , uSkyBlock , Vault , Head Database , MCDuels , SkyWars , EffectLib , IDisguise , Multiverse core , NoPlugin and Friday the 13th . Console log https://pastebin.com/d0Aef9xi . But when are playing only 2 Players it goes :/

**Comment by austinpilz** [comment]
You only send a few lines of the console, but from what I see, there are no errors being reported by Friday the 13th. 

Sometimes you can get kicked if you have low memory or a slow connection to the server. You have a LOT of other games running, they could interfere. F13 was designed to be run on its own server as part of a network
