### ISSUE TITLE
No skin updates. Spigot 1.12.

### ISSUE THREAD

**Issue by Fiks75** [austinpilz/FridayThe13th#4]
No skin updates. Spigot 1.12 errors. Please fix it.

16.07 23:26:07 [Server] WARN [FridayThe13th] Task #21 for FridayThe13th v1.4.1 generated an exception
16.07 23:26:07 [Server] INFO java.util.NoSuchElementException: null
16.07 23:26:07 [Server] INFO at com.google.common.collect.LinkedHashMultimap$ValueSet$1.next(LinkedHashMultimap.java:403) ~[server.jar:git-Spigot-7228328-af1c013]
16.07 23:26:07 [Server] INFO at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:496) ~[server.jar:git-Spigot-7228328-af1c013]
16.07 23:26:07 [Server] INFO at com.AustinPilz.FridayThe13th.Components.SkinChange.apply(SkinChange.java:48) ~[?:?]
16.07 23:26:07 [Server] INFO at com.AustinPilz.FridayThe13th.Components.Jason.prepareforGameplay(Jason.java:199) ~[?:?]
16.07 23:26:07 [Server] INFO at com.AustinPilz.FridayThe13th.Manager.Arena.PlayerManager.performInProgressActions(PlayerManager.java:436) ~[?:?]
16.07 23:26:07 [Server] INFO at com.AustinPilz.FridayThe13th.Manager.Arena.GameManager.beginGame(GameManager.java:383) ~[?:?]
16.07 23:26:07 [Server] INFO at com.AustinPilz.FridayThe13th.Manager.Arena.GameManager.changeGameStatus(GameManager.java:365) ~[?:?]
16.07 23:26:07 [Server] INFO at com.AustinPilz.FridayThe13th.Manager.Arena.GameManager.checkGameStatus(GameManager.java:245) ~[?:?]
16.07 23:26:07 [Server] INFO at com.AustinPilz.FridayThe13th.Runnable.GameStatusCheck.run(GameStatusCheck.java:17) ~[?:?]
16.07 23:26:07 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-7228328-af1c013]
16.07 23:26:07 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-7228328-af1c013]
16.07 23:26:07 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [server.jar:git-Spigot-7228328-af1c013]
16.07 23:26:07 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [server.jar:git-Spigot-7228328-af1c013]
16.07 23:26:07 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-7228328-af1c013]
16.07 23:26:07 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-7228328-af1c013]
16.07 23:26:07 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
16.07 23:26:13 [Server] INFO CONSOLE issued server command: /list
16.07 23:26:13 [Server] INFO Сейчас 2 из 50 игроков на сервере.
16.07 23:26:13 [Server] INFO default: Fiks75, vasya
16.07 23:28:07 [Server] INFO CONSOLE issued server command: /list
16.07 23:28:07 [Server] INFO Сейчас 2 из 50 игроков на сервере.
16.07 23:28:07 [Server] INFO default: Fiks75, vasya
16.07 23:28:16 [Server] INFO Fiks75 issued server command: /f13 leave
16.07 23:28:16 [Server] ERROR null
16.07 23:28:16 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'f13' in plugin FridayThe13th v1.4.1
16.07 23:28:16 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-7228328-af1c013]
16.07 23:28:16 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-7228328-af1c013]
16.07 23:28:16 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[server.jar:git-Spigot-7228328-af1c013]
16.07 23:28:16 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [server.jar:git-Spigot-7228328-af1c013]
16.07 23:28:16 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [server.jar:git-Spigot-7228328-af1c013]
16.07 23:28:16 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-7228328-af1c013]
16.07 23:28:16 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-7228328-af1c013]
16.07 23:28:16 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-7228328-af1c013]
16.07 23:28:16 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
16.07 23:28:16 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
16.07 23:28:16 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-7228328-af1c013]
16.07 23:28:16 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [server.jar:git-Spigot-7228328-af1c013]
16.07 23:28:16 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [server.jar:git-Spigot-7228328-af1c013]
16.07 23:28:16 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-7228328-af1c013]
16.07 23:28:16 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-7228328-af1c013]
16.07 23:28:16 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
16.07 23:28:16 [Server] INFO Caused by: java.lang.NullPointerException
16.07 23:28:16 [Server] INFO at com.AustinPilz.FridayThe13th.Components.SkinChange.revert(SkinChange.java:79) ~[?:?]
16.07 23:28:16 [Server] INFO at com.AustinPilz.FridayThe13th.Components.Jason.removeSkin(Jason.java:621) ~[?:?]
16.07 23:28:16 [Server] INFO at com.AustinPilz.FridayThe13th.Manager.Arena.PlayerManager.performPlayerCleanupActions(PlayerManager.java:589) ~[?:?]
16.07 23:28:16 [Server] INFO at com.AustinPilz.FridayThe13th.Manager.Arena.PlayerManager.performEndGameActions(PlayerManager.java:524) ~[?:?]
16.07 23:28:16 [Server] INFO at com.AustinPilz.FridayThe13th.Manager.Arena.GameManager.endGame(GameManager.java:393) ~[?:?]
16.07 23:28:16 [Server] INFO at com.AustinPilz.FridayThe13th.Manager.Arena.PlayerManager.onplayerQuit(PlayerManager.java:348) ~[?:?]
16.07 23:28:16 [Server] INFO at com.AustinPilz.FridayThe13th.Command.CommandHandler.onCommand(CommandHandler.java:270) ~[?:?]
16.07 23:28:16 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-7228328-af1c013]
16.07 23:28:16 [Server] INFO ... 15 more
16.07 23:28:28 [Server] INFO vasya issued server command: /f13 leave
16.07 23:28:34 [Disconnect] User vasya has disconnected, reason: Disconnected

**Comment by austinpilz** [comment]
I've never seen this kind of issue before. I can't see what happened before the issue, did Jason leave the arena before the game ended? Try restarting (not reloading) your server and try again. Also - your server must be in "online" mode, I'm assuming.

**Comment by Fiks75** [comment]
My server online-mode=false. Restarting the server did not solve the problem. Yes. Jason left the arena when one player remained in the arena.

**Comment by austinpilz** [comment]
I'm not sure what to tell you. When I tested on an offline mode server, it didn't update the skins but it didn't make an error. Please download and install Friday the 13th. 1.4.3 and give that a shot.
